name: yandex_place_picker
description: Place Picker utilising Yandex MapKit
version: 0.0.1
author: Ivan Semkin <ivan@semkin.ru>
homepage: https://github.com/vanyasem/yandex_place_picker

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.15.8
  intl_translation: ^0.17.5

  yandex_mapkit: ^0.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/
